# Generated by Django 4.2.1 on 2023-06-02 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_plays'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plays',
            new_name='Play',
        ),
    ]
