# Generated by Django 4.2.1 on 2023-06-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_plays_play'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('F', 'Friendly Local Game Store'), ('O', 'Online'), ('B', 'Big Box Store')], default=0, max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='play',
            name='date',
            field=models.DateField(verbose_name='play date'),
        ),
    ]
