# Generated by Django 4.2.1 on 2023-06-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_store_alter_play_options_alter_play_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stores',
            field=models.ManyToManyField(to='main_app.store'),
        ),
    ]
